[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
tweet_escrow = "Bh3Y47AqrAWBGCtFmSKqBdyA7tNtHGdD2yrYF9apSWJH"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
