[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
tweet_escrow = "Bh3Y47AqrAWBGCtFmSKqBdyA7tNtHGdD2yrYF9apSWJH"

[programs.devnet]
tweet_escrow = "Bh3Y47AqrAWBGCtFmSKqBdyA7tNtHGdD2yrYF9apSWJH"

[programs.testnet]
tweet_escrow = "Bh3Y47AqrAWBGCtFmSKqBdyA7tNtHGdD2yrYF9apSWJH"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://api.testnet.solana.com"
wallet = "./authority.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
